language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: make test
deploy:
  provider: heroku
  app: flask-restful-todo
  on:
    repo: erkarl/flask-restful-todo
  api_key:
    secure: wwMAVR6WiWLxFzELxSqRzp04MqaaR8CdBPuY+ZkPpp+U8UGC2/Meld5jIpOId1DElufIObAY9aHdZ22wfsGErgGln55WIGJQt+0EEyxjf+OBM0819n5PX6B5LkXqdxPHoT4CHJ26j5FOrpmsZ7MMGTJdPrjN1kbZkbUKJcV4uLs=
